name: Go package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build windows binary
        run: GOOS=windows go build

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: binaries
      #     path: tabletennis_result_converter.exe

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tabletennis_result_converter.exe
          asset_name: tabletennis_result_converter_windows-amd64.zip
          asset_content_type: application/zip
